### ISSUE TITLE
[Feature Req] Allow dragging a video onto RVP to play video.

### ISSUE THREAD

**Issue by Scroungers** [Peanutccino/Random-Video-Player#3]
Potentially add to next in queue, or play video on drag/drop and resume queue afterwards.

**Comment by Peanutccino** [comment]
I'll see what I can do. Thanks for the suggestion!

**Comment by Peanutccino** [comment]
Implemented the function and already enhanced on it. Quiet happy with it for now.

Thanks for the suggestion <3
