### ISSUE TITLE
Windows 11 ARM64 - can't launch RVP

### ISSUE THREAD

**Issue by Micr0waves** [Peanutccino/Random-Video-Player#5]
First off, hat's off to you, i love this player and the functionalities! i have a favourites list of 130 and love to just set it to shuffle thru them for a fast fresh experience. Thank you lots for this! i hope you continue to support us :D
As for my problem, i'm trying to run RVP on windows 11 ARM64, but i get this error when trying to run it:
This was with Version 1.50

Exception: LoadDLL failed: Mpv.NET.API.MpvAPIException:
Failed to load Mpv DLL. Error code: 1114
(A dynamic link library (DLL) initialization routine failed.
at Mpv.NET.API.MpvFunctions.LoadDIl(String dllPath)
dlIPath was: C:\Torrents\with funscript tools\win11
rvp\RVP-v1.50\RVP\ib\libmpv-2.dll

With version 1.41 i get this:
Exception: Failed to load Mpv DLL. .NET apps by default are
32-bit so make sure you're loading the 32-bit DLL.

I hope you can do anything with this info, let me know if i can give you more details or test anything.
I laso completely understand if you don't want to put time into fixing this.

**Comment by Peanutccino** [comment]
Hey, thanks for your feedback!

I had another user reporting the same error, altough it was on a x86 windows 10 system. Ultimately, the root cause was some kind of incompability with the libmpv itself. 

Therefore it would be awesome if you could try replacing my included libmpv-2.dll (which is a bit older now) with the latest version and see if it works with that.

You can grab it here: https://sourceforge.net/projects/mpv-player-windows/files/libmpv/

Simply choose the topmost mpv-dev-x86-x64 download, unpack the 7z file and replace the old libmpv-2.dll with the fresh extracted one under RVP\lib\

If thise works for you too, that would be amazing and I will pack RVP with the latest version for the future.

**Comment by Micr0waves** [comment]
Hey, gladly :)
I just tried what you suggested. I downloaded the following file: 
[mpv-dev-x86_64-v3-20240901-git-7c672e3.7z](https://sourceforge.net/projects/mpv-player-windows/files/libmpv/mpv-dev-x86_64-v3-20240901-git-7c672e3.7z/download)

This is what i got as an error this time, i think it is the same error.

Exception: LoadDLL failed: Mpv.NET.API.MpvAPIException:
Failed to load Mpv DLL. Error code: 1114
(A dynamic link library (DLL) initialization routine failed.
at Mpv.NET.API.MpvFunctions.LoadDII(String dllPath)
dlIPath was: C:\Torrents\with funscript\tools\win11
rvp\RVP-v1.50\RVP\lib\libmpv-2.dll

If i try with the other Variants from the latest release:
i686:
Exception: LoadDLL failed: Mpv.NET.API.MpvAPIException:
Failed to load Mpv DLL. Error code: 193
0 at Mpv.NET.API.MpvFunctions.LoadDII(String dllPath)
dlIPath was: C:\Torrents\with funscript\tools\win11
rvp\RVP-v1.50\RVP\ib\libmpv-2.dll

mpv-dev-x86_64-20240901-git-7c672e3:
It is working!!! nice one my dude, thank you lots

I have one question for you, i have over 400 clips with scripts in a mess of a directory.
now i have about 150 favourites saved as a list in RVP. Is there any way you know of that would help me move/copy/export only my favourites to a specific directory?

Thank you so much for you help again. much apreciate your work.

**Comment by Peanutccino** [comment]
Thanks so much for your effort! I will include the working libmpv in the next update!

For the list stuff; Currently there is no easy way. The only function is the "move file" button thingy but I see that this would require quiet some time/work for a whole list. 

I liked the idea to move a complete list to a specified directory though, so I think about a way to implement that :)

**Comment by Peanutccino** [comment]
Hey there,

the new update adds a feature to the listbrowser window.

You can now use "Move list" to either move or copy all current list entries to a specified location!

Just make sure to save the list afterwards as every edit made in the listbrowser is only for the temporary list and doesn't alter any of the saved files.

**Comment by Micr0waves** [comment]
oh wow! thank you so much, i'll check this out right now :)

**Comment by Micr0waves** [comment]
So i tried it, my 133 Favourites copied over from all the random places like a charm! thank you sooo much <3
the only feedback that i have for this option, is a checkmark to include the funscripts aswell ;)

btw. 1.52 worked on my arm64 machine out of the box without issues, so you built it perfectly.
